---
slug: walnuts
filename: walnuts
title: Wally and the Walnuts
subtitle: An Alternate View of Economics
description: Residents of a remote mountain valley learn the value of cooperation (and the challenges of finance) when their village adopts the prized and durable walnut as currency.
author: The Wallyworkers
copyright: 1991
uuid: 88e622c2-22bb-4df8-bc1c-71296646e789
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
